# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mclass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mclass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mage', models.IntegerField()),
                ('maddress', models.TextField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapp.Mclass1')),
            ],
        ),
    ]
