# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('tage', models.IntegerField()),
                ('taddress', models.TextField(max_length=50)),
            ],
        ),
    ]
